name: 友链自助申请
description: 自助添加友链，必须先挂我方链接
title: "[友链申请] "
labels: ["友链申请"]
body:
  - type: markdown
    attributes:
      value: |
        ### 申请规则
        1. 务必先在你的友链页面挂上本站
        本站名称：hhwzk博客
        本站地址：https://hhwzk.cc.cd
        2. 填写完整信息提交，机器人自动审核
  - type: input
    id: site_name
    attributes:
      label: 你的网站名称
    validations:
      required: true
  - type: input
    id: site_url
    attributes:
      label: 你的网站主页
      placeholder: https://xxx.com
    validations:
      required: true
  - type: input
    id: friend_page_url
    attributes:
      label: 你的友链页面地址
      placeholder: https://xxx.com/friends
    validations:
      required: true
  - type: textarea
    id: site_desc
    attributes:
      label: 站点简介
  - type: input
    id: site_avatar
    attributes:
      label: 头像图片直链